matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug VERBOSE=1 CXX_FLAGS="-std=c++11 -Wdeprecated"
script:
  - git ls-files txt/!*.txt | xargs clang-format -i && git diff --exit-code
  - cd src
  - git ls-files | xargs clang-format -i && git diff --exit-code
  - cd ..
  - cd tests
  - git ls-files */googletest/* | xargs clang-format -i && git diff --exit-code
